#!/bin/sh
# Setup a machine for Sublime Text 3
#set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages
cd "$sublime_dir"

rm -rf "$sublime_dir/Theme - Soda"
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"

rm -rf "$sublime_dir/Theme - Spacegray"
git clone https://github.com/kkga/spacegray/ "Theme - Spacegray"

rm -rf "$sublime_dir/Theme - Flatland"
git clone git://github.com/thinkpixellab/flatland.git "Theme - Flatland"

rm -rf "$sublime_dir/Theme - Tomorrow.*"
# Tomorrow includes many other implementations - we want only Sublime/Textmate
git clone git://github.com/chriskempson/tomorrow-theme "Theme - Tomorrow.tmp"
mv "Theme - Tomorrow.tmp/textmate" "Theme - Tomorrow"
rm -rf "Theme - Tomorrow.tmp"

git clone https://github.com/chriskempson/base16-textmate.git "Color Scheme - Base16"
