#!/bin/sh
# Setup a machine for Sublime Text 3
#set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages

#mv "$sublime_dir/User" "$sublime_dir/User.backup"
rm -rf "$sublime_dir/User"
ln -s "$ZSH/sublime/Packages/User" "$sublime_dir"