# Rails aliases:
alias b="bundle exec"
alias deploy="bundle exec cap production deploy"
alias log="tail -f log/development.log"
alias testlog="tail -f log/test.log"
alias prolog="bundle exec cap production tail_log"
alias restart="touch tmp/restart.txt;echo '*** App restarted ***'"
alias migrate="bundle exec rake db:migrate"
alias rollback="bundle exec rake db:rollback"
alias redo="bundle exec rake db:migrate:redo"
alias deploy="bundle exec cap production deploy"
alias routes="bundle exec rake routes"
alias resque="bundle exec rake resque:work QUEUE=\*"